services:
  # 前端服务
  frontend:
    build: ./frontend
    container_name: esg_ai_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
      - REACT_APP_SUPABASE_URL=https://idbudhqpealkqvjwfgnj.supabase.co
      - REACT_APP_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkYnVkaHFwZWFsa3F2andmZ25qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxODA0NDEsImV4cCI6MjA1Nzc1NjQ0MX0.vfo9EcXJ_Sh5b_tbSw0WsqTMY7oKFcVgxcO7G5ReINU
    networks:
      - esg_ai_network
    depends_on:
      - backend

  # 后端服务
  backend:
    build: ./backend
    container_name: esg_ai_backend
    environment:
      - SUPABASE_URL
      - SUPABASE_KEY
      - DATABASE_URL
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - esg_ai_network
    command: >
      sh -c "alembic upgrade head &&
             python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

networks:
  esg_ai_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  postgres_data:
