services:
  # 前端服务
  frontend:
    build: ./frontend
    container_name: esg_ai_frontend
    ports:
      - "3000:3000"
    environment:
      # - REACT_APP_API_URL=http://54.234.135.166:8000/api/v1
      - REACT_APP_API_URL=http://localhost:8000/api/v1

    networks:
      - esg_ai_network
    depends_on:
      - backend

  # 后端服务
  backend:
    build: ./backend
    container_name: esg_ai_backend
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - esg_ai_network
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # 数据库服务
  postgres:
    image: postgres:14
    container_name: esg_ai_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: esg_ai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - esg_ai_network

networks:
  esg_ai_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  postgres_data: 